name = "PlutoPlotly"
uuid = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.0"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[compat]
AbstractPlutoDingetjes = "1.1"
PlotlyBase = "0.8"
julia = "1.6"
